controller:
  ## The name of the Ingress Controller daemonset or deployment.
  name: controller

  ## The kind of the Ingress Controller installation - deployment or daemonset.
  kind: deployment
  hostNetwork: true

  image:
    ## The image repository of the Ingress Controller.
    repository: nginx/nginx-ingress
    tag: "3.7.0"
    pullPolicy: IfNotPresent

  ## The resources of the Ingress Controller pods.
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  # limits:
  #   cpu: 1
  #   memory: 1Gi
  
  ## The resources for the Ingress Controller init container which is used when readOnlyRootFilesystem is set to true.
  initContainerResources:
    requests:
      cpu: 100m
      memory: 128Mi
  extraContainers: []
  replicaCount: 1
  ingressClass:
    name: nginx
    create: true

  service:
    ## Creates a service to expose the Ingress Controller pods.
    create: true

    ## The type of service to create for the Ingress Controller.
    type: NodePort