# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: 
    app: keycloak-postgres
  name: keycloak-postgres
  annotations:    
    {{- if .Values.deploymentAnnotations }}
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
    {{- end }}  
spec:
  serviceName: keycloak-postgres
  selector:
    matchLabels:
      app: keycloak-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-postgres
      name: keycloak-postgrespostgres
    spec:
      containers:
      - name: keycloak-postgres
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}
        # - secretRef:
        #     name: {{ .Chart.Name }}      
        image: postgres:15.5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
          {{- range .Values.volumeMounts }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}

        ports:
        - name: kc-postgres
          containerPort: 5432
          protocol: TCP
        env:
          - name: POSTGRES_USER
            value: {{ .Values.envFromConfigMap.KC_DB_USERNAME }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}
                key: KC_DB_PASSWORD                                                        
        # Volume Claim
      dnsPolicy: ClusterFirst
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.volumes.awsEKSCluster }}
      - name: {{ .Values.volumes.vol_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.pvc_name }}
      {{- else }}
      - hostPath:
          path: {{ .Values.volumes.efs_path }}
          type: {{ .Values.volumes.efs_type }}
        name: {{ .Values.volumes.vol_name }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-postgres
  name: keycloak-postgres
spec:
  type: ClusterIP
  ports:
  - name: kc-postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: keycloak-postgres
---
##### This PVC will be used for the postgres components
{{- if .Values.volumes.awsEKSCluster }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  labels:
    app: keycloak-postgres
  name: keycloak-postgres
  # namespace: demo-india                  ### Change namespace as require
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}   
  storageClassName: {{ .Values.volumes.className }}
{{- end }}