apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: {{ include "keycloak.password" . }}
  KC_DB_PASSWORD: {{ include "keycloak.db_password" . }}